(function () {
  const LANGUAGE_STORAGE_KEY = "shareclaw-ui-language-v1";
  const TARGET_BUTTON_SELECTOR = "#platformSwitchBtn";
  const TRANSLATABLE_ATTRS = ["aria-label", "title", "placeholder", "data-placeholder"];
  const originalTextByNode = new WeakMap();
  const originalAttrsByElement = new WeakMap();
  let activeLanguage = loadLanguage();
  let isApplyingLanguage = false;
  let originalDocumentTitle = document.title;
  let observer = null;
  let pendingApply = false;

  const zhToEn = {
    "北京易动纷享科技有限责任公司": "Beijing Easy Mobile Share Technology Co., Ltd.",
    "方案1": "Plan 1",
    "方案2": "Plan 2",
    "全部": "All",
    "搜索": "Search",
    "名称、描述、标签...": "name, description, tags...",
    "Search 名称、描述、标签...": "Search name, description, tags...",
    "名称": "Name",
    "对话": "Conversation",
    "创建时间": "Created time",
    "预置": "Presets",
    "企信": "Messenger",
    "提醒": "Notifications",
    "待办": "To-dos",
    "草稿箱": "Drafts",
    "帮助": "Help",
    "一级导航": "Primary navigation",
    "二级导航": "Secondary navigation",
    "工作": "Work",
    "日程": "Calendar",
    "更多": "More",
    "时钟": "Clock",
    "成员": "Members",
    "设置": "Settings",
    "打开设置": "Open settings",
    "更多操作": "More actions",
    "收起菜单": "Collapse menu",
    "展开菜单": "Expand menu",
    "新建会话": "New chat",
    "销售记录": "Record",
    "现场会议": "Review",
    "在线会议": "Meeting",
    "自动化": "Automation",
    "智能体": "Agents",
    "文档库": "Documents",
    "历史会话": "Conversation history",
    "返回ShareAgent": "Back to ShareAgent",
    "返回": "Back",
    "个性化设置": "Personalization",
    "运行状态": "Runtime status",
    "基本信息": "Basic info",
    "智能体广场": "Agent marketplace",
    "技能": "Skills",
    "技能中心": "Skill center",
    "管理技能": "Manage Skills",
    "管理": "Manage",
    "市场": "Marketplace",
    "发送消息": "Send a message",
    "思考中...": "Thinking...",
    "思考中": "Thinking",
    "消息输入": "Message input",
    "AI输入区域": "AI input area",
    "AI对话内容": "AI conversation",
    "添加附件": "Add attachment",
    "切换工作模式或智能体": "Switch work mode or agents",
    "切换Work模式或Agents": "Switch work mode or agents",
    "指定智能体模式": "Select Agents mode",
    "指定Agents模式": "Select Agents mode",
    "问答": "Q&A",
    "问答模式": "Q&A mode",
    "规划模式": "Planning mode",
    "规划": "Planning",
    "清除智能体": "Clear agent",
    "语音": "Voice",
    "您好Scott，今天我有什么能帮您？": "Hello Scott, how can I help today?",
    "由 ShareAgent · 今日 09:00 自动生成": "Auto-generated by ShareAgent · Today 09:00",
    "待回复": "Pending reply",
    "重点客户异动晨检": "Key Account Change Morning Check",
    "海岳智能制造集团客户近况": "Haiyue Intelligent Manufacturing Group Updates",
    "客户会议纪要回填 CRM": "Backfill Customer Meeting Notes to CRM",
    "创建客户 · 百子湾": "Create Customer · Baiziwan",
    "海岳智能制造集团客户近况": "Haiyue Intelligent Manufacturing Group Updates",
    "帮我查看海岳智能制造集团近况和后续怎么做": "Show me the latest on Haiyue Intelligent Manufacturing Group and what to do next",
    "帮我查看Haiyue Intelligent Manufacturing Group近况和后续怎么做": "Show me the latest on Haiyue Intelligent Manufacturing Group and what to do next",
    "线索池清理与分发": "Lead Pool Cleanup and Assignment",
    "帮我总结这个月的销售报表": "Summarize this month's sales report",
    "重点客户经营周报": "Key Account Weekly Business Report",
    "帮我查找过去30天的总聊天对话": "Find all chats from the past 30 days",
    "续费预警复盘提醒": "Renewal Risk Review Reminder",
    "会议前准备": "Pre-meeting Preparation",
    "停滞商机复盘提醒": "Stalled Opportunity Review Reminder",
    "大客户拜访简报": "Key Account Visit Brief",
    "合同审批超时提醒": "Contract Approval Timeout Reminder",
    "给我平均响应时间的趋势": "Show average response time trend",
    "显示过去30天的对话趋势条形图": "Show a bar chart of conversation trends from the past 30 days",
    "ShareAgent - 任务": "ShareAgent - Tasks",
    "ShareAgent - 文档库": "ShareAgent - Documents",
    "ShareAgent - 设置": "ShareAgent - Settings",
    "ShareAgent - 企信": "ShareAgent - Messenger",
    "ShareAgent - 智能体": "ShareAgent - Agents",
    "ShareAgent - 独立对话": "ShareAgent - Standalone Chat",
    "设置你的 ShareAgent 个性化信息": "Set up your ShareAgent personalization",
    "可以为你的ShareAgent取个性化的名字": "Give your ShareAgent a personalized name",
    "定义ShareAgent的称呼、定位与沟通风格，决定ShareAgent的语气、主动性与输出形式。": "Define ShareAgent's name, role, and communication style to shape its tone, initiative, and output format.",
    "请输入": "Please enter",
    "ShareAgent 名称": "ShareAgent name",
    "ShareAgent 设定": "ShareAgent settings",
    "设定": "Settings",
    "关闭设置弹窗": "Close settings dialog",
    "设置分类": "Settings categories",
    "授权": "Authorization",
    "对象授权配置": "Object authorization",
    "配置 ShareAgent 对不同业务对象可执行的操作范围。": "Configure which actions ShareAgent can perform for each business object.",
    "自定义": "Custom",
    "永远询问": "Always ask",
    "不再询问": "Don't ask again",
    "展开新建选项": "Expand create options",
    "新建选项": "Create options",
    "新建，本次对话不再询问": "Create, don't ask again in this chat",
    "新建，以后不再询问": "Create, don't ask again",
    "以后所有对话，新建客户不再询问。": "For all future chats, creating customers will not ask again.",
    "前往授权设置": "Go to authorization settings",
    "客户新建授权": "Customer create authorization",
    "客户编辑授权": "Customer edit authorization",
    "线索新建授权": "Lead create authorization",
    "线索编辑授权": "Lead edit authorization",
    "日程新建授权": "Calendar create authorization",
    "日程编辑授权": "Calendar edit authorization",
    "设置已保存": "Settings saved",
    "侧边栏交互方案": "Sidebar interaction plan",
    "新建对象 · 橘子科技": "Create object · Orange Tech",
    "编辑对象 · 橘子科技": "Edit object · Orange Tech",
    "更新对象 · 橘子科技": "Update object · Orange Tech",
    "复杂查询": "Complex query",
    "帮我查一下本季度名下有进行中商机的客户，并列出每个客户关联的商机和订单。": "Find customers under my name with active opportunities this quarter, and list each customer's related opportunities and orders.",
    "新建定时任务": "Create scheduled task",
    "我要做一个定时任务，每天早上九点给我发送AI新闻资讯": "Create a scheduled task to send me AI news every day at 9 AM.",
    "新建对象": "Create object",
    "创建对象": "Create object",
    "编辑对象": "Edit object",
    "更新对象": "Update object",
    "删除对象": "Delete object",
    "删除客户 · 橘子科技": "Delete customer · Orange Tech",
    "删除客户": "Delete customer",
    "删除橘子科技": "Delete Orange Tech",
    "AI对话 · 删除对象": "AI chat · Delete object",
    "AI对话 · 创建对象": "AI chat · Create object",
    "AI对话 · 编辑对象": "AI chat · Edit object",
    "展开全部": "Expand all",
    "收起全部": "Collapse all",
    "帮我录入一个新客户，公司叫橘子科技，对接人叫李明，感觉是个大单！": "Enter a new customer: company Orange Tech, contact Li Ming, likely a large deal.",
    "帮我把刚才开会的客户录进去": "Enter the customer from the meeting",
    "帮我创建一个客户：橘子科技有限责任公司 ，是个重要客户 ，互联网行业，联系人是李明，电话是13500000000": "Create a customer: Orange Technology Co., Ltd., key account, internet industry, contact Li Ming, phone 13500000000",
    "好的，我从刚才的会议记录里整理了以下信息：": "Okay, I pulled the following information from the meeting notes:",
    "好的，我从刚才的会议记录里整理了以下信息:": "Okay, I pulled the following information from the meeting notes:",
    "李明的手机号是多少？": "What is Li Ming's mobile number?",
    "橘子科技属于哪个行业？": "Which industry does Orange Tech belong to?",
    "客户创建完成": "Customer created",
    "创建商机": "Create opportunity",
    "补充详细信息": "Add details",
    "添加相关联系人": "Add related contacts",
    "已生成客户创建草稿，请确认：": "Customer creation draft generated. Please confirm:",
    "已生成客户编辑草稿，请确认：": "Customer edit draft generated. Please confirm:",
    "已生成客户更新草稿，请确认：": "Customer update draft generated. Please confirm:",
    "客户“橘子科技有限责任公司”已创建。": "Customer “Orange Technology Co., Ltd.” created.",
    "客户“橘子科技有限责任公司”已编辑。": "Customer “Orange Technology Co., Ltd.” edited.",
    "客户“橘子科技有限责任公司”已更新。": "Customer “Orange Technology Co., Ltd.” updated.",
    "已取消新建客户“橘子科技有限责任公司”。": "Canceled creating customer “Orange Technology Co., Ltd.”.",
    "已取消编辑客户“橘子科技有限责任公司”。": "Canceled editing customer “Orange Technology Co., Ltd.”.",
    "已取消更新客户“橘子科技有限责任公司”。": "Canceled updating customer “Orange Technology Co., Ltd.”.",
    "当前客户关联3条商机和5位联系人，本操作将会删除该客户及其全部关联数据": "This customer is linked to 3 opportunities and 5 contacts. This action will delete the customer and all related data.",
    "确定要删除「橘子科技」吗？此操作不可撤销。": "Delete “Orange Tech”? This action cannot be undone.",
    "确认删除": "Confirm delete",
    "已删除客户“橘子科技”。": "Customer “Orange Tech” deleted.",
    "已取消删除客户“橘子科技”。": "Canceled deleting customer “Orange Tech”.",
    "已生成定时任务创建草稿，请确认：": "Scheduled task creation draft generated. Please confirm:",
    "好的，我来帮你创建这个每日AI资讯定时任务": "Okay, I will help you create this daily AI news scheduled task.",
    "好的，我来帮你创建这个每日AI资讯ScheduledTask": "Okay, I will help you create this daily AI news scheduled task.",
    "✅ 定时任务“每日 AI 资讯推送”已创建。": "✅ Scheduled task “Daily AI News Push” created.",
    "已取消创建定时任务“每日 AI 资讯推送”。": "Canceled creating scheduled task “Daily AI News Push”.",
    "操作已经取消": "Operation canceled",
    "仍有信息需要补充：": "More information still needed:",
    "仍有信息需要补充:": "More information still needed:",
    "创建·定时任务": "Create · Scheduled task",
    "每日 AI 资讯推送": "Daily AI News Push",
    "每天 09:00 · 推送至会话": "Every day 09:00 · Push to chat",
    "执行规则": "Schedule rule",
    "推送渠道": "Push channel",
    "任务内容": "Task content",
    "AI 新闻资讯": "AI news",
    "ShareClaw会话": "ShareClaw chat",
    "推送至会话": "Push to chat",
    "详细信息": "Details",
    "创建定时任务": "Create scheduled task",
    "定时任务": "Scheduled task",
    "已进入 AI 模拟对话": "Entered AI simulation chat",
    "基于你发送的内容，我已经整理出客户数据卡片，并生成了一份可继续查看和转发的 PDF 卡片。": "Based on what you sent, I prepared a customer data card and generated a PDF card you can view and forward.",
    "客户信号": "Customer signals",
    "远峰软件服务有限公司": "Yuanfeng Software Service Co., Ltd.",
    "远峰软件服务需求纪要.pdf": "Yuanfeng Software Service Requirements Notes.pdf",
    "商机阶段：需求确认": "Opportunity stage: Requirements confirmation",
    "负责人：陈琳": "Owner: Chen Lin",
    "陈琳": "Chen Lin",
    "客户当前最关心线索分发、销售记录回填和周报自动化。": "The customer currently cares most about lead distribution, sales record backfill, and weekly report automation.",
    "内部需求方数量较多，需要一份统一版本作为后续沟通底稿。": "There are many internal requesters, so a unified version is needed as the basis for follow-up communication.",
    "如果先形成纪要 PDF，会显著降低多轮澄清成本。": "Creating a notes PDF first will significantly reduce the cost of repeated clarification.",
    "把核心诉求整理成需求纪要并同步给所有干系人。": "Organize the core needs into requirement notes and share them with all stakeholders.",
    "补一页方案边界说明，避免预期过度扩张。": "Add one page explaining solution boundaries to avoid over-expanded expectations.",
    "下轮沟通聚焦优先级排序，而不是继续收集新需求。": "Focus the next conversation on priority ranking instead of continuing to collect new requirements.",
    "商机阶段：方案评审": "Opportunity stage: Solution review",
    "方案评审": "Solution review",
    "负责人：刘志强": "Owner: Liu Zhiqiang",
    "刘志强": "Liu Zhiqiang",
    "近 7 天客户活跃度提升 18%，但关键审批人仍未确认最终预算。": "Customer activity increased 18% in the last 7 days, but the key approver has not confirmed the final budget.",
    "售前方案已进入第三轮评审，客户更关注交付周期和上线节奏。": "The pre-sales proposal has entered the third review round, and the customer cares more about delivery timeline and launch pace.",
    "当前最优动作是补一页 ROI 摘要，帮助业务方推动内部立项。": "Best next action is to add a one-page ROI summary to help the business side drive internal approval.",
    "补充高层汇报版摘要，重点回答预算回报和落地路径。": "Add an executive summary focused on budget return and implementation path.",
    "锁定采购、IT 与业务三方联络窗口，减少重复沟通。": "Lock the procurement, IT, and business contacts to reduce repeated communication.",
    "把下一次会议目标收敛到“确认试点范围与决策时间表”。": "Narrow the next meeting goal to confirming pilot scope and decision timeline.",
    "以下是你本季度有进行中商机的客户，点击可展开查看各客户详情：": "Customers with active opportunities this quarter are listed below. Click to expand each customer for details:",
    "关联商机": "Related opportunities",
    "关联订单": "Related orders",
    "查看全部": "View all",
    "深圳匠人科技": "Shenzhen Artisan Tech",
    "广州匠人科技": "Guangzhou Artisan Tech",
    "杭州云杉信息技术有限公司": "Hangzhou Yunshan Information Technology Co., Ltd.",
    "成都启明医疗科技": "Chengdu Qiming Medical Technology",
    "南京智行物流集团": "Nanjing Zhixing Logistics Group",
    "苏州长河装备制造": "Suzhou Changhe Equipment Manufacturing",
    "武汉蓝桥教育咨询": "Wuhan Lanqiao Education Consulting",
    "李思远": "Li Siyuan",
    "王志伟": "Wang Zhiwei",
    "李川": "Li Chuan",
    "周敏": "Zhou Min",
    "陈浩": "Chen Hao",
    "赵楠": "Zhao Nan",
    "刘洋": "Liu Yang",
    "孙悦": "Sun Yue",
    "SaaS 平台年度续约": "SaaS platform annual renewal",
    "数据中台建设项目": "Data middle platform project",
    "售后工单系统升级": "After-sales ticket system upgrade",
    "渠道订单协同系统": "Channel order collaboration system",
    "会员营销增长包": "Membership marketing growth package",
    "零售数据看板": "Retail data dashboard",
    "智能销售分析平台": "Intelligent sales analytics platform",
    "数据仓库升级项目": "Data warehouse upgrade project",
    "院区客户服务系统": "Hospital customer service system",
    "运输调度协同项目": "Transport dispatch collaboration project",
    "客服质检自动化": "Customer service QA automation",
    "设备售后知识库": "Equipment after-sales knowledge base",
    "经销商门户升级": "Dealer portal upgrade",
    "招生线索运营系统": "Enrollment lead operations system",
    "2026-Q2 服务续费订单": "2026-Q2 service renewal order",
    "坐席扩容采购订单": "Seat expansion purchase order",
    "数据接口服务订单": "Data API service order",
    "基础平台订阅订单": "Base platform subscription order",
    "运维支持服务订单": "Operations support service order",
    "API 调用包订单": "API call package order",
    "试点实施服务订单": "Pilot implementation service order",
    "门店账号采购订单": "Store account purchase order",
    "培训服务订单": "Training service order",
    "BI 报表订阅订单": "BI report subscription order",
    "咨询服务订单": "Consulting service order",
    "试运行服务订单": "Trial operation service order",
    "标准版账号订单": "Standard edition account order",
    "实施人天订单": "Implementation man-day order",
    "培训服务采购": "Training service purchase",
    "线索包服务订单": "Lead package service order",
    "普通客户": "Standard customer",
    "订单金额": "Order amount",
    "谈判中": "In negotiation",
    "方案制作中": "Solution drafting",
    "技术评审": "Technical review",
    "报价中": "Quoting",
    "方案沟通": "Solution discussion",
    "POC准备": "POC preparation",
    "商务谈判": "Business negotiation",
    "履约中": "In fulfillment",
    "待回款": "Payment pending",
    "待验收": "Acceptance pending",
    "待签约": "Signing pending",
    "已确认": "Confirmed",
    "等待您的回答...": "Waiting for your response...",
    "等待您的回答…": "Waiting for your response...",
    "新建 · 客户": "Create · Customer",
    "新建": "Create",
    "创建来源": "Source",
    "编辑来源": "Source",
    "更新来源": "Source",
    "执行对象": "Target object",
    "AI 对话": "AI chat",
    "AI对话": "AI chat",
    "客户对象": "Customer object",
    "客户名称": "Customer name",
    "客户级别": "Customer level",
    "客户性质": "Customer type",
    "联系人": "Contact",
    "初步判断": "Initial assessment",
    "大单意向": "Large deal intent",
    "手机号": "Mobile number",
    "性质": "Type",
    "企业规模": "Company size",
    "是否首次接触": "First contact",
    "民营Enterprise": "Private enterprise",
    "民营企业": "Private enterprise",
    "100-500 人": "100-500 people",
    "500-1000 人": "500-1000 people",
    "是": "Yes",
    "否": "No",
    "未填写": "Not filled",
    "重要客户": "Key account",
    "新客户": "New customer",
    "新客户 · 互联网行业": "New customer · Internet industry",
    "互联网行业": "Internet industry",
    "橘子科技有限责任公司": "Orange Technology Co., Ltd.",
    "橘子科技": "Orange Tech",
    "李明": "Li Ming",
    "线索": "Lead",
    "创建客户": "Create customer",
    "编辑客户": "Edit customer",
    "查询客户": "Query customer",
    "提交": "Submit",
    "ShareAgent 引导页": "ShareAgent guide",
    "创建自动化": "Create automation",
    "创建技能": "Create skill",
    "创建任务": "Create task",
    "创建": "Create",
    "已创建": "Created",
    "所有任务": "All tasks",
    "执行日志": "Execution logs",
    "进行中的任务": "Active tasks",
    "已过期的任务": "Expired tasks",
    "全部任务记录": "All task records",
    "全部类型": "All types",
    "全部状态": "All statuses",
    "任务记录": "Task records",
    "类型": "Type",
    "状态": "Status",
    "开始日期到结束日期": "Start date to end date",
    "开始日期": "Start date",
    "结束日期": "End date",
    "查看执行日志": "View execution logs",
    "通过AI对话创建": "Create with AI chat",
    "手动创建": "Create manually",
    "Manual创建": "Create manually",
    "编辑": "Edit",
    "执行中": "Running",
    "成功": "Success",
    "失败": "Failed",
    "上次执行": "Last run",
    "定时": "Scheduled",
    "手动": "Manual",
    "每个工作日 上午09:00": "Every weekday 09:00 AM",
    "每个工作日 上午10:00": "Every weekday 10:00 AM",
    "每个工作日 下午05:30": "Every weekday 5:30 PM",
    "每周一 上午10:30": "Every Monday 10:30 AM",
    "每周二 上午09:30": "Every Tuesday 09:30 AM",
    "每周三 下午03:00": "Every Wednesday 3:00 PM",
    "每周五 下午12:00": "Every Friday 12:00 PM",
    "每个工作日": "Every weekday",
    "每周一": "Every Monday",
    "每周二": "Every Tuesday",
    "每周三": "Every Wednesday",
    "每周五": "Every Friday",
    "每天": "Every day",
    "上午": "AM",
    "下午": "PM",
    "上午09:00": "09:00 AM",
    "上午09:30": "09:30 AM",
    "上午10:00": "10:00 AM",
    "上午10:30": "10:30 AM",
    "下午03:00": "3:00 PM",
    "下午05:30": "5:30 PM",
    "下午12:00": "12:00 PM",
    "小时": "hour",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "销售助手": "Sales assistant",
    "会议助手": "Meeting assistant",
    "售前Agent": "Pre-sales Agent",
    "客户成功Agent": "Customer Success Agent",
    "商机洞察Agent": "Opportunity Insights Agent",
    "法务助手": "Legal assistant",
    "销售推进": "Sales advancement",
    "商机巡检": "Opportunity inspection",
    "续约助手": "Renewal assistant",
    "Customer successAgent": "Customer Success Agent",
    "已扫描高价值客户活跃度、工单升级和商机推进变化，生成晨检摘要并同步提醒对应销售负责人优先跟进。": "Scanned high-value account activity, ticket escalations, and opportunity progress changes; generated a morning-check summary and notified the responsible sales owner for priority follow-up.",
    "每天 09:00 扫描高价值客户的活跃度、工单升级和商机推进变化，生成 CRM 晨检摘要并 @ 对应销售负责人。": "Every day at 09:00, scan high-value account activity, ticket escalations, and opportunity progress changes, then generate a CRM morning-check summary and @mention the responsible sales owner.",
    "已提取会议录音中的客户诉求、行动项和风险项，并完成纪要整理与客户、商机跟进记录回填。": "Extracted customer requests, action items, and risks from the meeting recording, then completed notes cleanup and backfilled customer and opportunity follow-up records.",
    "已提取会议录音中的客户诉求、行动项和风险点，并Done纪要整理与客户、商机跟进记录回填。": "Extracted customer requests, action items, and risks from the meeting recording, then completed notes cleanup and backfilled customer and opportunity follow-up records.",
    "按 CRM 线索评分规则完成重复线索清洗，自动流转可转化线索，并标记需人工复核的异常分发项。": "Cleaned duplicate leads by CRM scoring rules, routed convertible leads automatically, and marked abnormal assignments for manual review.",
    "按 CRM 线索评分规则Done重复线索清洗，自动流转可转化线索，并标记需人工复核的异常分发项。": "Cleaned duplicate leads by CRM scoring rules, routed convertible leads automatically, and marked abnormal assignments for manual review.",
    "已汇总本周客户拜访、续费风险、回款进展和下周动作建议，并生成发送给区域负责人的经营周报。": "Summarized this week's customer visits, renewal risks, payment progress, and next-week action suggestions, then generated the weekly business report for the regional owner.",
    "已识别 30 天内到期且健康分下降的客户，补充续费策略提醒，并同步客户成功经理安排后续拜访。": "Identified customers expiring within 30 days with declining health scores, added renewal strategy reminders, and synced with the Customer Success manager to arrange follow-up visits.",
    "已识别 30 天内到期且健康分下降的客户，补充续费策略Notifications，并同步Customer success经理安排后续拜访。": "Identified customers expiring within 30 days with declining health scores, added renewal strategy notifications, and synced with the Customer Success manager to arrange follow-up visits.",
    "已扫描高价值客户活跃度、工单升级和商机推进变化，生成 CRM 晨检摘要并 @ 对应销售负责人。": "Scanned high-value account activity, ticket escalations, and opportunity progress changes, then generated a CRM morning-check summary and @mentioned the responsible sales owner.",
    "提取会议录音中的客户诉求、行动项和风险项，自动整理纪要并同步到客户与商机的跟进记录。": "Extract customer requests, action items, and risks from meeting recordings, then automatically organize notes and sync follow-up records to customers and opportunities.",
    "按 CRM 线索评分规则清洗重复和低质量线索，并把可转化线索自动分配给对应行业销售池。": "Clean duplicate and low-quality leads by CRM scoring rules, then automatically assign convertible leads to the matching industry sales pool.",
    "汇总本周客户拜访、续费风险、回款进展和下周动作建议，自动输出给区域负责人周报。": "Summarize this week's customer visits, renewal risks, payment progress, and next-week action suggestions, then automatically produce a weekly report for the regional owner.",
    "识别 30 天内到期且健康分下降的客户，自动提醒客户成功经理补充续费策略和拜访计划。": "Identify customers expiring within 30 days whose health scores are declining, then automatically remind the Customer Success manager to add renewal strategies and visit plans.",
    "关注当天 AI 领域重要动态，并结合客户背景生成会前重点提示。": "Track important AI updates for the day and combine them with customer context to generate key pre-meeting prompts.",
    "筛选两周未推进的重点商机，提醒销售补充风险说明和下一步推进建议。": "Find key opportunities with no progress for two weeks and remind sales to add risk notes and next-step suggestions.",
    "生成拜访前客户简报，整合关键人关系、历史成交、待解决事项和近期互动摘要。": "Generate a pre-visit customer brief that combines key stakeholder relationships, historical deals, open issues, and recent interaction summaries.",
    "自动识别超时未审批合同，提醒对应负责人并附上合同金额、折扣说明和风险备注。": "Automatically identify overdue unapproved contracts, remind the responsible owner, and include contract amount, discount notes, and risk remarks.",
    "创建成功": "Created successfully",
    "任务历史": "Task history",
    "业务生成结果": "Business outputs",
    "当前任务还没有沉淀到文档库的产出结果。": "This task has not produced any document-library outputs yet.",
    "今天": "Today",
    "昨天": "Yesterday",
    "刚刚执行": "Just executed",
    "刚刚": "Just now",
    "历史记录": "History record",
    "历史执行记录": "Historical execution record",
    "执行失败，待复核": "Execution failed, pending review",
    "当前筛选下没有企业预置智能体。": "No enterprise preset agents match the current filters.",
    "当前筛选下没有市场智能体。": "No marketplace agents match the current filters.",
    "当前还没有添加技能。": "No skills have been added yet.",
    "当前筛选下没有技能。": "No skills match the current filters.",
    "当前筛选下没有我创建的内容。": "No created items match the current filters.",
    "当前筛选下没有可批量操作的内容。": "No batch-editable items match the current filters.",
    "当前还没有选中需要共享的内容。": "No items selected for sharing yet.",
    "没有匹配的会话。": "No matching conversations.",
    "全文预览": "Full preview",
    "我创建的": "Created by me",
    "自动化任务": "Automation tasks",
    "企业预置": "Enterprise presets",
    "市场营销": "Marketing",
    "个人助理": "Personal assistant",
    "销售": "Sales",
    "运营": "Operations",
    "营销": "Marketing",
    "财务": "Finance",
    "售前": "Pre-sales",
    "售后": "After-sales",
    "客户服务": "Customer service",
    "智能体(旧版)": "Legacy Agents",
    "Agents(旧版)": "Legacy Agents",
    "旧版Agents": "Legacy Agents",
    "旧版智能体": "Legacy agents",
    "项目启动报告": "Project Kickoff Report",
    "项目": "Project",
    "产品": "Product",
    "法务": "Legal",
    "审计": "Audit",
    "调研": "Research",
    "体验": "Experience",
    "预测": "Forecast",
    "客户": "Customer",
    "负责人": "Owner",
    "商机": "Opportunity",
    "跟进记录": "Follow-up records",
    "应收单": "Receivables",
    "合同": "Contract",
    "报告": "Report",
    "清单": "List",
    "查询": "View",
    "未读": "Unread",
    "下一步": "Next step",
    "最近触达": "Last touch",
    "健康度": "Health",
    "方案确认": "Solution confirmation",
    "服务": "Service",
    "企业": "Enterprise",
    "共享": "Shared",
    "刘涛": "Liu Tao",
    "赵晨": "Zhao Chen",
    "销售一部": "Sales Dept. 1",
    "自建": "Custom",
    "文档清洗": "Document Cleanup",
    "自动识别 PDF、表格与网页中的结构化字段，支持标准化输出。": "Automatically identifies structured fields in PDFs, spreadsheets, and web pages, with standardized output.",
    "自动识别 PDF、表格与网页中的结构化字段，支持标准化输出.": "Automatically identifies structured fields in PDFs, spreadsheets, and web pages, with standardized output.",
    "AI 销售建议 CRM 模型设计方案": "AI Sales Recommendation CRM Model Design Plan",
    "AI Sales建议 CRM 模型设计方案": "AI Sales Recommendation CRM Model Design Plan",
    "百度集团客户流失警告": "Baidu Group Customer Churn Warning",
    "百度集团Customer流失警告": "Baidu Group Customer Churn Warning",
    "CRM平台产品经理本周周报": "CRM Platform Product Manager Weekly Report",
    "重点客户跟进清单": "Key Account Follow-up List",
    "重点Customer跟进List": "Key Account Follow-up List",
    "停滞商机清单": "Stalled Opportunity List",
    "停滞OpportunityList": "Stalled Opportunity List",
    "推进话术建议": "Advancement Script Suggestions",
    "第三代CRM浪潮下的战略对策建议": "Strategic Recommendations for the Third-generation CRM Wave",
    "AI Native 时代战略转型研讨会PPT": "AI Native Era Strategic Transformation Seminar PPT",
    "纷享价值观3.0.pdf": "FX Value Principles 3.0.pdf",
    "自动汇总商机背景、团队分工与关键风险，生成标准项目启动材料。": "Automatically summarizes opportunity background, team responsibilities, and key risks to generate standard kickoff materials.",
    "审计支持": "Audit Support",
    "归集财务佐证材料、生成问题清单，并辅助输出审计回复说明。": "Collects financial supporting materials, generates issue lists, and helps draft audit response notes.",
    "归集财务凭证和材料、生成问题清单，并辅助输出审计说明。": "Collects financial vouchers and materials, generates issue lists, and helps draft audit notes.",
    "竞品分析报告": "Competitive Analysis Report",
    "对比竞品卖点、价格与功能变化，快速输出销售与产品双视角报告。": "Compares competitor selling points, pricing, and feature changes to quickly produce sales and product perspectives.",
    "商业计划书": "Business Plan",
    "根据行业、客户与方案信息，一键生成标准商业计划书与汇报大纲。": "Generates a standard business plan and presentation outline from industry, customer, and solution information.",
    "根据行业、客户与方案信息，一键生成标准商业计划书结构。": "Generates a standard business-plan structure from industry, customer, and solution information.",
    "销售预测官": "Sales Forecast Officer",
    "读取漏斗进展与历史回款数据，自动推演季度目标达成率。": "Reads funnel progress and historical payment data to estimate quarterly target attainment automatically.",
    "Customer success经理": "Customer Success Manager",
    "客户成功经理": "Customer Success Manager",
    "根据客户分层、续约风险和健康分，为客户成功团队生成跟进建议。": "Generates follow-up suggestions for the Customer Success team based on customer tiers, renewal risks, and health scores.",
    "根据客户分层、续约风险和健康分，为Customer success团队生成跟进建议。": "Generates follow-up suggestions for the Customer Success team based on customer tiers, renewal risks, and health scores.",
    "演示脚本助手": "Demo Script Assistant",
    "根据行业与角色快速生成标准 Demo 讲解脚本，支持会前排练。": "Quickly generates standard demo scripts by industry and role, supporting pre-meeting rehearsal.",
    "财务问答官": "Finance Q&A Assistant",
    "面向业务团队解释常见财务口径、审批规则和预算使用规范。": "Explains common finance definitions, approval rules, and budget usage policies for business teams.",
    "面向业务团队解释常见财务口径、审批规则和预算问题。": "Explains common finance definitions, approval rules, and budget questions for business teams.",
    "客户晨会简报": "Customer Morning Brief",
    "由销售运营共享给你，自动汇总昨日商机推进与客户异动。": "Shared by sales operations, automatically summarizing yesterday's opportunity progress and customer changes.",
    "续约风险雷达": "Renewal Risk Radar",
    "由客户成功团队共享，跟踪到期客户、服务工单和回访记录。": "Shared by the Customer Success team to track expiring customers, service tickets, and follow-up records.",
    "由Customer success团队共享，跟踪到期客户、健康分和服务记录。": "Shared by the Customer Success team to track expiring customers, health scores, and service records.",
    "客户洞察": "Customer insights",
    "客户洞察智能体": "Customer Insights Agent",
    "客户 / 商机 / 跟进记录": "Customer / Opportunity / Follow-up records",
    "客户流失风险": "Customer churn risk",
    "当我负责的客户健康度下降50%以下时通知我": "Notify me when the health score of one of my accounts drops below 50%.",
    "客户跟进助理": "Customer follow-up assistant",
    "每天帮我汇总重点客户的新动态、待回消息和下一步建议，输出可直接执行的跟进清单。": "Summarize key account updates, pending replies, and next-step recommendations every day, then output an actionable follow-up checklist.",
    "主动推进": "Proactive",
    "简洁直接": "Concise",
    "稳妥专业": "Steady and professional",
    "客户动态": "Customer updates",
    "会议纪要": "Meeting notes",
    "客户简报": "Customer brief",
    "资料整理": "Material organization",
    "续约雷达": "Renewal radar",
    "待办提醒": "To-do reminders",
    "风险提示": "Risk alerts",
    "CRM产品": "CRM product",
    "亲切": "Friendly",
    "文字总结": "Text summary",
    "标准篇幅": "Standard length",
    "使用行业术语": "Use industry terminology",
    "个人设置": "Personal settings",
    "企业预置": "Enterprise presets",
    "公司平台": "Company platform",
    "共享给同事": "Share with colleagues",
    "删除": "Delete",
    "完成": "Done",
    "取消": "Cancel",
    "保存": "Save",
    "确认": "Confirm",
    "关闭": "Close",
    "更新": "Update",
    "下载": "Download",
    "转发": "Forward",
    "同步到CRM": "Sync to CRM",
    "复制链接": "Copy link",
    "跳转对话": "Open chat",
    "聊天": "Chat",
    "文件": "Files",
    "图片": "Images",
    "视频": "Videos",
    "看板": "Board",
    "工作消息": "Work messages",
    "企业互联": "Enterprise network",
    "客群 腾讯科技（21）": "Customer Group Tencent Tech (21)",
    "华东运营组（36）": "East China Operations Group (36)",
    "客户成功": "Customer success",
    "售后角色": "Post-sales roles",
    "续约提醒助理": "Renewal reminder assistant",
    "持续关注续约客户、工单波动和健康分变化，适合客户成功与售后角色。": "Continuously tracks renewal accounts, ticket changes, and health-score shifts for customer success and post-sales roles.",
    "持续监控我负责客户的续约节点、工单趋势和健康分变化，及时提醒我处理高风险客户。": "Continuously monitor renewal milestones, ticket trends, and health-score changes for my accounts, and remind me to handle high-risk customers in time.",
    "销售跟进助理": "Sales follow-up assistant",
    "每次客户会议前，帮我整合客户背景、最近沟通纪要和风险点，并输出一页会前简报。": "Before each customer meeting, combine customer background, recent notes, and risks into a one-page pre-meeting brief.",
    "在每次客户会议前，帮我整合客户背景、最近沟通纪要和风险点，并输出一页会前简报。": "Before each customer meeting, combine customer background, recent notes, and risks into a one-page pre-meeting brief.",
    "继续补充跟进建议": "Add more follow-up suggestions",
    "重新生成客户简报": "Regenerate customer brief",
    "查看 PDF 全文": "View full PDF",
    "生成重点客户跟进清单": "Generate key account follow-up list",
    "列出停滞商机": "List stalled opportunities",
    "生成推进话术": "Generate advancement script",
    "生成催款提醒文案": "Generate payment reminder copy",
    "导出风险订单清单": "Export risky order list",
    "生成日程版计划": "Generate calendar plan",
    "拆分到个人任务": "Split into individual tasks",
    "生成周会汇报版": "Generate weekly meeting report",
    "生成客户挽回话术": "Generate customer recovery script",
    "拉取最近沟通记录": "Pull recent communication records",
    "安排高层拜访建议": "Suggest executive visit plan",
    "生成差额补齐计划": "Generate gap-closing plan",
    "梳理本月高概率商机": "Review high-probability opportunities this month",
    "生成冲刺提醒文案": "Generate sprint reminder copy",
    "自动创建销售记录": "Auto-create sales record",
    "生成续费提醒话术": "Generate renewal reminder script",
    "生成内部协同清单": "Generate internal collaboration checklist",
    "使用该技能": "Use this skill",
    "将技能共享给同事": "Share this skill with colleagues",
    "将技能发布到公司平台": "Publish this skill to the company platform",
    "查看POC场景覆盖度": "View POC scenario coverage",
    "导出报价方案": "Export quotation plan",
    "查看功能缺口分析": "View feature gap analysis",
    "销售记录（小米集团续费跟进）": "Sales record (Xiaomi Group renewal follow-up)",
    "创建时间：04-17 10:20": "Created: 04-17 10:20",
    "客户会议纪要回填清单": "Customer Meeting Notes Backfill List",
    "CustomerMeeting notes回填List": "Customer Meeting Notes Backfill List",
    "昨日会议回填结果.md": "Yesterday Meeting Backfill Results.md",
    "海岳方案评审会议": "Haiyue Solution Review Meeting",
    "售后演示准备": "After-sales Demo Preparation",
    "任务": "Task",
    "已处理 12秒": "Processed in 12 sec",
    "已处理 36秒": "Processed in 36 sec",
    "已处理 1分30秒": "Processed in 1 min 30 sec",
    "北京纷享销客科技有限公司": "Beijing Fxiaoke Technology Co., Ltd.",
    "产品选配清单": "Product configuration list",
    "回款闭环自动处理流程": "Payment Close-loop Automation",
    "回款闭环处理报告.pdf": "Payment Close-loop Processing Report.pdf",
    "昨日回款闭环摘要.pdf": "Yesterday Payment Close-loop Summary.pdf",
    "待回款风险客户清单": "At-risk Receivables Customer List",
    "重点客户异动晨检报告.pdf": "Key Account Change Morning Check Report.pdf",
    "高优先级客户跟进清单": "High-priority Customer Follow-up List",
    "【客户】海岳智能制造集团有限公司": "[Customer] Haiyue Intelligent Manufacturing Group Co., Ltd.",
    "海岳智能制造集团": "Haiyue Intelligent Manufacturing Group",
    "任务提示词": "Task prompt",
    "CRM任务配置": "CRM task config",
    "本次手动执行": "Current manual run",
    "任务配置": "Task config",
    "本次执行方式": "Execution method",
    "执行状态": "Execution status",
    "执行智能体": "Executing agent",
    "关键发现": "Key findings",
    "建议动作": "Recommended actions",
    "资源": "Resources",
    "海岳智能制造集团最近跟进情况分析": "Haiyue Intelligent Manufacturing Group Recent Follow-up Analysis",
    "基于近 14 天的跟进数据，我为你梳理了关键推进信号，并生成了可转发的客户简报。": "Based on the last 14 days of follow-up data, I summarized the key progress signals and generated a forwardable customer brief.",
    "整体跟进节奏偏慢，近一周高价值客户平均 4.2 天才有一次有效触达，低于建议的 2 天节奏。": "The overall follow-up pace is slow. In the past week, high-value customers averaged one effective touch every 4.2 days, below the recommended 2-day cadence.",
    "3 个重点商机停留在“方案确认”阶段超过 10 天，其中 1 个客户最近没有新的决策人反馈。": "Three key opportunities have stayed in the \"Solution confirmation\" stage for more than 10 days, and one customer has had no recent decision-maker feedback.",
    "客户对价格和交付周期的异议增多，说明当前推进已经从需求沟通转向成交博弈阶段。": "Customer objections around pricing and delivery timelines have increased, indicating the work has moved from requirements alignment into deal negotiation.",
    "下一步建议": "Next-step recommendations",
    "今天内优先约 3 个高概率客户做 15 分钟同步，确认采购节点和最新内部意见。": "Prioritize 15-minute syncs with three high-probability customers today to confirm procurement milestones and the latest internal feedback.",
    "把还停在方案确认阶段的项目补一版“价值回顾 + 差异化卖点”摘要，压缩来回澄清成本。": "Add a \"value recap + differentiated selling points\" summary for projects still in solution confirmation to reduce clarification cycles.",
    "对超过 7 天没有推进的商机单独拉表，明确负责人、阻塞点和下次动作时间。": "Create a separate list for opportunities with no progress for more than 7 days, clarifying owners, blockers, and next-action timing.",
    "您可点击卡片查看客户详情和客户简报：": "Click the cards to view customer details and the customer brief:",
    "海岳智能制造集团有限公司": "Haiyue Intelligent Manufacturing Group Co., Ltd.",
    "海岳智能制造集团客户简报.pdf": "Haiyue Intelligent Manufacturing Group Customer Brief.pdf",
    "已生成 PDF": "PDF generated",
    "本次晨检扫描重点客户池、商机阶段和近 7 天互动记录，识别出 3 个推进节奏异常客户，其中 1 个进入高优先级跟进。": "This morning check scanned the key account pool, opportunity stages, and interaction records from the past 7 days, identifying three customers with abnormal progress cadence, including one moved into high-priority follow-up.",
    "上海宏景装备的报价审批已完成，但客户采购节点仍未确认，存在下周推进空窗。": "Shanghai Hongjing Equipment's quotation approval is complete, but the customer's procurement milestone is still unconfirmed, creating a possible progress gap next week.",
    "深圳拓远电子近 5 次互动平均响应时长升至 18 小时，高于重点客户建议阈值。": "Shenzhen Tuoyuan Electronics' average response time across the last five interactions has risen to 18 hours, above the recommended threshold for key accounts.",
    "今天内由刘志强补发海岳价值回顾和交付周期说明，锁定下一次采购确认时间。": "Have Liu Zhiqiang resend Haiyue's value recap and delivery timeline today, then lock the next procurement confirmation time.",
    "将上海宏景装备加入本周高概率商机清单，提醒负责人同步采购侧最新口径。": "Add Shanghai Hongjing Equipment to this week's high-probability opportunity list and remind the owner to sync the latest procurement-side position.",
    "对响应时长异常客户生成跟进提醒，优先安排电话触达而非继续等待Messenger回复。": "Generate follow-up reminders for customers with abnormal response times and prioritize phone outreach instead of waiting for Messenger replies.",
    "CRM 客户健康分": "CRM customer health score",
    "商机阶段停留时长": "Opportunity stage dwell time",
    "最近跟进记录": "Recent follow-up records",
    "Messenger互动响应": "Messenger interaction response",
    "我已先抽取客户线索里的关键信息": "I have extracted the key information from the customer lead",
    "我已先抽取Customer线索里的关键信息": "I have extracted the key information from the customer lead",
    "已识别信息": "Identified information",
    "还缺少": "Still missing",
    "项信息，请在对话卡片里补充。": "items. Please complete them in the conversation card.",
    "项信息，请在底部卡片里补充。": "items. Please complete them in the bottom card.",
    "补充关键信息": "Complete key information",
    "查看待补充问题": "View questions to complete",
    "重点客户（推荐）": "Key account (recommended)",
    "VIP客户": "VIP customer",
    "普通用户": "Standard user",
    "互联网": "Internet",
    "制造业": "Manufacturing",
    "消费品": "Consumer goods",
    "采购": "Procurement",
    "业务部门Leader": "Business department leader",
    "查看本次执行的历史摘要。": "Review the historical summary for this run.",
    "查看本次执行生成的摘要与建议动作。": "Review the summary and recommended actions generated by this run.",
    "如需复盘，可回到执行日志查看相邻记录。": "For review, return to execution logs to inspect adjacent records.",
    "如需再次执行，可返回任务列表手动触发。": "To run it again, return to the task list and trigger it manually.",
    "如需继续推进，可在当前对话中补充跟进要求。": "To continue, add follow-up requirements in this conversation.",
    "回到任务列表可继续查看其他执行记录。": "Return to the task list to view other execution records.",
    "已根据当前任务提示生成一轮新的任务执行摘要。": "Generated a new task execution summary from the current task prompt.",
    "Sources：": "Sources: ",
    "该阶段任务": "Stage tasks",
    "上一个客户": "Previous customer",
    "下一个客户": "Next customer",
    "暂无可展示内容": "Nothing to show",
    "当前页签下还没有匹配的数据。": "No matching data for this tab yet.",
    "移动端 App 定制开发": "Mobile app custom development",
    "商机金额": "Opportunity amount",
    "阶段": "Stage",
    "需求确认": "Requirements confirmation",
    "百子湾": "Baiziwan",
    "客户等级": "Customer tier",
    "所属行业": "Industry",
    "联系人职位": "Contact role",
    "联系电话": "Phone number",
    "这个客户等级你想先怎么标？是直接上 VIP，还是先标重点客户观望？": "How should this customer be classified first? Upgrade directly to VIP, or mark as a key account to observe?",
    "这个Customer等级你想优先怎么标？ 是直接上 VIP，还是先标重点Customer观察？": "How should this customer be classified first? Upgrade directly to VIP, or mark as a key account to observe?",
    "橘子科技是哪个行业的？": "Which industry is Orange Technology in?",
    "当前接触的联系人李明，他的角色是？（可多选）": "What is the role of the current contact, Li Ming? Multiple selections allowed.",
    "他的联系电话你知道吗？": "Do you know his phone number?",
    "请输入联系电话": "Enter phone number",
    "CEO / 老板": "CEO / Owner",
    "IT 负责人": "IT owner",
    "VIP客户": "VIP customer",
    "记录类型": "Record type",
    "字段状态": "Field status",
    "会议时间": "Meeting time",
    "任务状态": "Task status",
    "优先级": "Priority",
    "截止时间": "Due time",
    "待补充": "Pending completion",
    "待处理": "Pending",
    "补交付材料": "complete delivery materials",
    "确认演示环境": "confirm demo environment",

    // Create/Edit task dialog
    "创建自动化任务": "Create Automation Task",
    "编辑自动化任务": "Edit Automation Task",
    "关闭创建任务弹窗": "Close create task dialog",
    "关闭编辑任务弹窗": "Close edit task dialog",
    "保存并启用": "Save & Enable",
    "仅保存": "Save only",
    "保存修改并启用": "Save changes & Enable",
    "仅保存修改": "Save changes only",
    "任务信息配置": "Task configuration",
    "任务指令": "Task instructions",
    "输入指令": "Enter instructions",
    "选择智能体": "Select agent",
    "执行频率": "Execution frequency",
    "周期": "Recurring",
    "按间隔": "By interval",
    "单次": "One-time",
    "每周": "Every week",
    "每双周": "Every two weeks",
    "每月": "Every month",
    "每": "Every",
    "分钟": "min",
    "选择星期": "Select days",
    "选择日期": "Select date",
    "选择月份": "Select month",
    "周六": "Sat",
    "周日": "Sun",
    "1月": "Jan",
    "2月": "Feb",
    "3月": "Mar",
    "4月": "Apr",
    "5月": "May",
    "6月": "Jun",
    "7月": "Jul",
    "8月": "Aug",
    "9月": "Sep",
    "10月": "Oct",
    "11月": "Nov",
    "12月": "Dec",
    "时效及范围": "Validity & scope",
    "配置生效时间范围": "Set validity period",
    "（默认始终生效）": "(always active by default)",
    "推送到纷享企信": "Push to Messenger",
    "选择起始时间": "Select start time",
    "企信发送给": "Send via Messenger to",
    "选择企信接收方": "Select Messenger recipients",
    "添加企信接收方": "Add Messenger recipients",
    "移除": "Remove",
    "未命名任务": "Untitled task",
    "已保存修改：": "Changes saved: ",
    "已保存并启用：": "Saved & enabled: ",
    "已保存任务：": "Task saved: ",
    "已保存并启用任务：": "Task saved & enabled: "
  };

  const phraseEntries = Object.entries(zhToEn).sort((a, b) => b[0].length - a[0].length);

  function loadLanguage() {
    try {
      return window.localStorage.getItem(LANGUAGE_STORAGE_KEY) === "en" ? "en" : "zh";
    } catch (error) {
      return "zh";
    }
  }

  function persistLanguage(language) {
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch (error) {
      // Local previews may block storage; the visible state still updates.
    }
  }

  function hasCjk(value) {
    return /[\u3400-\u9fff]/.test(value || "");
  }

  function normalizeTranslatedValue(value) {
    if (!value) {
      return value;
    }

    const monthNames = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ];

    return value
      .replace(/(\d{4})年0?(\d{1,2})月0?(\d{1,2})日/g, (_, year, month, day) => {
        const monthName = monthNames[Number(month) - 1] || month;
        return `${monthName} ${Number(day)}, ${year}`;
      })
      .replace(/已处理\s*(\d+)分0?(\d+)秒/g, "Processed in $1 min $2 sec")
      .replace(/已处理\s*(\d+)秒/g, "Processed in $1 sec")
      .replace(/已处理\s*(\d+)个步骤/g, "Processed $1 steps")
      .replace(/有\s*(\d+)\s*个字段没有获取到，请补充一下[:：]?/g, "$1 fields are missing. Please add them")
      .replace(/帮我把刚才开会的Customer录进去/g, "Enter the customer from the meeting")
      .replace(/民营Enterprise/g, "Private enterprise")
      .replace(/AI 模拟Conversation/g, "AI simulation chat")
      .replace(/Customer数据卡片/g, "customer data card")
      .replace(/Customer信号/g, "Customer signals")
      .replace(/Lead分发/g, "lead distribution")
      .replace(/Sales Record回填/g, "sales record backfill")
      .replace(/Record回填/g, "record backfill")
      .replace(/周报Automation/g, "weekly report automation")
      .replace(/Forward的 PDF/g, "forwardable PDF")
      .replace(/我要做一个ScheduledTask，Every day早上九点给我发送AI新闻资讯/g, "Create a scheduled task to send me AI news every day at 9 AM.")
      .replace(/已生成ScheduledTaskCreate草稿，请Confirm[:：]?/g, "Scheduled task creation draft generated. Please confirm:")
      .replace(/操作已经Cancel/g, "Operation canceled")
      .replace(/仍有信息需要补充[:：]?/g, "More information still needed:")
      .replace(/opportunity stage: 方案评审/g, "Opportunity stage: Solution review")
      .replace(/Owner: 刘志强/g, "Owner: Liu Zhiqiang")
      .replace(/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)(\d{1,2})日/g, "$1 $2")
      .replace(/\b(January|February|March|April|May|June|July|August|September|October|November|December)(\d{1,2})日/g, "$1 $2")
      .replace(/每日AI资讯ScheduledTask/g, "daily AI news scheduled task")
      .replace(/CreateScheduledTask/g, "Create scheduled task")
      .replace(/ScheduledTask/g, "scheduled task")
      .replace(/Every day早上九点/g, "every day at 9 AM")
      .replace(/Every day 09:00 · 推送至Conversation/g, "Every day 09:00 · Push to chat")
      .replace(/Every day 09:00/g, "Every day 09:00")
      .replace(/ShareClawConversation/g, "ShareClaw chat")
      .replace(/执行Rule/g, "Schedule rule")
      .replace(/Push channel/g, "Push channel")
      .replace(/帮我查一下本季度名下有进行中Opportunity的Customer，并列出Every个Customer关联的Opportunity和订单[.。]?/g, "Find customers under my name with active opportunities this quarter, and list each customer's related opportunities and orders.")
      .replace(/以下是你本季度有进行中Opportunity的Customer，点击可展开查看各customer details[:：]?/g, "Customers with active opportunities this quarter are listed below. Click to expand each customer for details:")
      .replace(/(\d+)个Customer/g, "$1 customers")
      .replace(/(\d+)条Opportunity/g, "$1 opportunities")
      .replace(/(\d+)条订单/g, "$1 orders")
      .replace(/个Customer/g, " customers")
      .replace(/条Opportunity/g, " opportunities")
      .replace(/条订单/g, " orders")
      .replace(/共(\d+)个Customer/g, "$1 customers total")
      .replace(/（共(\d+) customers）/g, "($1 customers total)")
      .replace(/（(\d+)）/g, " ($1)")
      .replace(/View all\(/g, "View all (")
      .replace(/关联Opportunity/g, "Related opportunities")
      .replace(/关联订单/g, "Related orders")
      .replace(/进行中Opportunity/g, "Active opportunities")
      .replace(/订单: /g, "Orders: ")
      .replace(/Customer insightsAgents/g, "Customer Insights Agent")
      .replace(/Customer success/g, "Customer Success")
      .replace(/CustomerMeeting notes回填List/g, "Customer Meeting Notes Backfill List")
      .replace(/Customer线索/g, "customer lead")
      .replace(/Customer名称/g, "Customer name")
      .replace(/CustomerName/g, "Customer name")
      .replace(/Customer等级/g, "customer tier")
      .replace(/Customer简报/g, "customer brief")
      .replace(/Customer详情/g, "customer details")
      .replace(/Customer池/g, "customer pool")
      .replace(/Customer平均/g, "customers averaged")
      .replace(/Customer最近/g, "customer recently")
      .replace(/Customer对/g, "customer ")
      .replace(/Customer健康分/g, "customer health score")
      .replace(/OpportunityStage/g, "opportunity stage")
      .replace(/OpportunityList/g, "opportunity list")
      .replace(/Product经理/g, "product manager")
      .replace(/Sales建议/g, "sales recommendations")
      .replace(/Haiyue Intelligent Manufacturing Group近况/g, "Haiyue Intelligent Manufacturing Group updates")
      .replace(/海岳智能制造集团Group/g, "Haiyue Intelligent Manufacturing Group")
      .replace(/【Record】/g, "[Record]")
      .replace(/【Sales record】/g, "[Record]")
      .replace(/【Task】/g, "[Task]")
      .replace(/\[Record\](?=\S)/g, "[Record] ")
      .replace(/\[Task\](?=\S)/g, "[Task] ")
      .replace(/我已先抽取customer lead里的关键信息/g, "I have extracted the key information from the customer lead")
      .replace(/customer leadIdentified/g, "customer lead. Identified")
      .replace(/重点Customer观察/g, "key account to observe")
      .replace(/After-sales演示准备/g, "After-sales Demo Preparation")
      .replace(/Execution logs查看/g, "Execution logs")
      .replace(/Back任务列表Manual/g, "return to the task list and trigger it manually")
      .replace(/执行Status/g, "Execution status")
      .replace(/执行Agents/g, "Executing agent")
      .replace(/Sources：/g, "Sources: ")
      .replace(/【Customer】/g, "[Customer]")
      .replace(/(\d{1,2})月(\d{1,2})日/g, (_, month, day) => {
        const monthName = monthNames[Number(month) - 1] || month;
        return `${monthName} ${Number(day)}`;
      })
      .replace(/｜/g, "|")
      .replace(/、/g, ", ")
      .replace(/：/g, ": ")
      .replace(/。/g, ".");
  }

  function translateValue(value) {
    if (!value) {
      return value;
    }
    if (!hasCjk(value)) {
      return normalizeTranslatedValue(value);
    }

    const leading = value.match(/^\s*/)?.[0] || "";
    const trailing = value.match(/\s*$/)?.[0] || "";
    const trimmed = value.trim();

    if (zhToEn[trimmed]) {
      return normalizeTranslatedValue(`${leading}${zhToEn[trimmed]}${trailing}`);
    }

    let next = value;
    phraseEntries.forEach(([zh, en]) => {
      next = next.split(zh).join(en);
    });

    return normalizeTranslatedValue(next);
  }

  function ensureLanguageButtonStyle() {
    if (document.getElementById("languageSwitchInjectedStyles")) {
      return;
    }

    const style = document.createElement("style");
    style.id = "languageSwitchInjectedStyles";
    style.textContent = `
      .platform-switch-btn {
        height: 28px;
        padding: 6px 8px;
        display: inline-flex;
        align-items: center;
        gap: 4px;
        border: 0;
        border-radius: 6px;
        background: #fff;
        color: #545861;
        font: inherit;
        font-size: 12px;
        line-height: 16px;
        font-weight: 500;
        white-space: nowrap;
        cursor: pointer;
        flex: 0 0 auto;
      }

      .platform-switch-btn svg {
        width: 16px;
        height: 16px;
        flex: 0 0 auto;
      }

      #openCreatedBtn {
        width: auto;
        min-width: 96px;
        white-space: nowrap;
      }
    `;
    document.head.appendChild(style);
  }

  function ensureLanguageButton() {
    ensureLanguageButtonStyle();

    if (document.querySelector(TARGET_BUTTON_SELECTOR)) {
      return;
    }

    const topbarRight = document.querySelector(".topbar-right");
    if (!topbarRight) {
      return;
    }

    const button = document.createElement("button");
    button.className = "platform-switch-btn";
    button.id = "platformSwitchBtn";
    button.type = "button";
    button.setAttribute("aria-label", "English");
    button.innerHTML = `
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <path d="M16 8C16 3.58154 12.4185 0 8 0C3.58154 0 0 3.58154 0 8C0 12.4185 3.58154 16 8 16C12.4185 16 16 12.4185 16 8ZM11.4363 1.88752C11.4349 1.89082 11.4332 1.89398 11.4317 1.89728C13.5617 3.09792 15 5.38082 15 7.99999C15.0014 8.98638 14.7934 9.96185 14.3899 10.8619C14.0336 10.1789 13.5393 9.88405 12.782 9.93708C12.6518 9.94598 12.5356 9.95956 12.3824 9.9812L12.1588 10.0113L12.06 10.0219L12.0154 10.0236L11.9667 10.0211L11.9276 10.0126C11.8525 9.99096 11.755 9.92265 11.5937 9.75083L11.5187 9.67362C10.7067 8.87647 9.61466 8.88877 8.60666 9.50265C7.30806 10.293 7.38272 12.1393 9.05593 13.3039L9.13569 13.3611C9.68635 13.7697 9.89975 14.2105 9.80641 14.7645C9.23029 14.9181 8.6249 15 7.99999 15C4.1343 15 1.00001 11.8661 1.00001 7.99999C0.997459 6.34974 1.58061 4.75214 2.64564 3.49157C2.91503 3.78473 2.94006 4.1186 2.7394 4.59333L2.70122 4.68581C2.42716 5.3909 2.48019 5.97169 2.95958 6.33781C3.24425 6.55502 3.54334 6.61993 4.01849 6.62884L4.23358 6.63011L4.57424 6.62587L4.64467 6.62799L4.70788 6.6369C4.79697 6.65599 4.86909 6.70478 4.9497 6.8223L4.99467 6.89399L5.018 6.93514L5.07994 7.05563L5.14824 7.20411L5.20891 7.34454L5.31157 7.59399L5.43163 7.8952C5.82236 8.8875 6.88254 9.07629 7.66442 8.45053C8.38223 7.87611 8.64187 6.83078 8.24308 5.76593C8.21763 5.69848 8.19514 5.63442 8.17393 5.57375L8.11708 5.40193C8.1086 5.37478 8.10054 5.3489 8.09333 5.32345L8.05345 5.18175L8.03733 5.11812L8.01272 5.00484L7.99617 4.91066L7.98769 4.83515C7.98267 4.79789 7.98483 4.76002 7.99405 4.72357L7.9966 4.71848C7.9966 4.71933 7.99745 4.71975 7.99914 4.71975L8.07508 4.70194C8.19514 4.67563 8.36993 4.66333 8.6389 4.66333C9.67829 4.66333 10.4432 3.86745 11.1292 2.53109L11.2531 2.28206C11.3135 2.15788 11.3725 2.02953 11.4317 1.89728C11.4316 1.89723 11.4318 1.89732 11.4317 1.89728L11.4363 1.88752ZM9.69908 12.1991C8.82684 11.5513 8.81326 10.867 9.26805 10.59C9.84035 10.2417 10.3125 10.2442 10.6647 10.6205C11.0172 10.9968 11.349 11.2047 11.7316 11.2722L11.7567 11.2764L11.8699 11.2925C11.9263 11.2987 11.983 11.301 12.0396 11.2993L12.1627 11.2917L12.3154 11.2747L12.6314 11.2314L12.7562 11.2166L12.8707 11.2068C13.0735 11.1924 13.2114 11.2696 13.3493 11.6056L13.3925 11.7206L13.4146 11.7851L13.4587 11.928L13.4812 12.0065L13.5279 12.1805L13.5491 12.2679C12.8941 13.1187 12.0528 13.8081 11.0897 14.283C11.0164 13.5007 10.5751 12.8109 9.78308 12.2594L9.69908 12.1991ZM3.55012 2.59685C4.75964 1.59903 6.31024 1 8.00042 1C8.77261 0.999169 9.53959 1.12647 10.2701 1.37673C9.71478 2.60152 9.10599 3.39061 8.6389 3.39061L8.41617 3.39358C7.70387 3.41267 7.29066 3.53612 6.97927 3.95315C6.59957 4.46182 6.65769 5.16139 7.05181 6.21266C7.26181 6.77393 7.14727 7.23466 6.86939 7.45696C6.71794 7.57829 6.67169 7.56981 6.61654 7.42896L6.4723 7.07217L6.38109 6.85666L6.29242 6.65896L6.20588 6.47781L6.12018 6.31278C5.72224 5.57927 5.33236 5.35315 4.57467 5.35315L4.31927 5.35612H4.06515L4.01552 5.35527L3.9277 5.35103L3.82376 5.34254L3.83055 5.31709C3.85246 5.23943 3.87953 5.16332 3.91158 5.08927L3.954 4.98363C4.30527 4.07066 4.164 3.24042 3.55012 2.59685Z" fill="#91959E"></path>
      </svg>
      <span>English</span>
    `;

    const search = topbarRight.querySelector(".top-search");
    topbarRight.insertBefore(button, search || topbarRight.firstChild);
  }

  function updateLanguageButton() {
    ensureLanguageButton();
    const button = document.querySelector(TARGET_BUTTON_SELECTOR);
    if (!button) {
      return;
    }

    const fullPlatformSwitch = button.closest(".platform-switch");
    if (fullPlatformSwitch && fullPlatformSwitch.querySelector(".platform-switch-menu")) {
      const fixedLabel = button.querySelector("#platformSwitchLabel") || button.querySelector("span");
      if (fixedLabel) {
        fixedLabel.textContent = "切换方案";
      }
      button.setAttribute("aria-label", "切换方案");
      return;
    }

    const label = button.querySelector("span");
    if (label) {
      label.textContent = activeLanguage === "en" ? "中文" : "English";
    }
    button.setAttribute("aria-label", activeLanguage === "en" ? "切换到中文" : "English");
  }

  function shouldSkipTextNode(node) {
    const parent = node.parentElement;
    if (!parent) {
      return true;
    }

    return Boolean(parent.closest(`${TARGET_BUTTON_SELECTOR}, script, style, svg, canvas, textarea, input`));
  }

  function applyTextNode(node) {
    if (shouldSkipTextNode(node)) {
      return;
    }

    if (!originalTextByNode.has(node)) {
      originalTextByNode.set(node, node.nodeValue);
    }

    const original = originalTextByNode.get(node);
    node.nodeValue = activeLanguage === "en" ? translateValue(original) : original;
  }

  function getOriginalAttrMap(element) {
    let map = originalAttrsByElement.get(element);
    if (!map) {
      map = {};
      originalAttrsByElement.set(element, map);
    }
    return map;
  }

  function applyElementAttrs(element) {
    if (element.matches(TARGET_BUTTON_SELECTOR) || element.closest(TARGET_BUTTON_SELECTOR)) {
      return;
    }

    const originalMap = getOriginalAttrMap(element);

    TRANSLATABLE_ATTRS.forEach((attr) => {
      if (!element.hasAttribute(attr)) {
        return;
      }
      if (!(attr in originalMap)) {
        originalMap[attr] = element.getAttribute(attr);
      }

      const original = originalMap[attr];
      element.setAttribute(attr, activeLanguage === "en" ? translateValue(original) : original);
    });
  }

  function walkAndApply(root) {
    if (!root) {
      return;
    }

    if (root.nodeType === Node.TEXT_NODE) {
      applyTextNode(root);
      return;
    }

    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) {
      return;
    }

    if (root.nodeType === Node.ELEMENT_NODE) {
      applyElementAttrs(root);
    }

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, {
      acceptNode(node) {
        if (node.nodeType === Node.ELEMENT_NODE && node.matches("script, style, svg, canvas")) {
          return NodeFilter.FILTER_REJECT;
        }
        if (node.nodeType === Node.ELEMENT_NODE && node.matches(TARGET_BUTTON_SELECTOR)) {
          return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      }
    });

    while (walker.nextNode()) {
      const node = walker.currentNode;
      if (node.nodeType === Node.TEXT_NODE) {
        applyTextNode(node);
      } else if (node.nodeType === Node.ELEMENT_NODE) {
        applyElementAttrs(node);
      }
    }
  }

  function applyLanguage(root = document.body) {
    if (isApplyingLanguage) {
      return;
    }

    isApplyingLanguage = true;
    document.documentElement.lang = activeLanguage === "en" ? "en" : "zh-CN";
    document.title = activeLanguage === "en" ? translateValue(originalDocumentTitle) : originalDocumentTitle;
    ensureLanguageButton();
    walkAndApply(root);
    updateLanguageButton();
    isApplyingLanguage = false;
  }

  function scheduleApply() {
    if (pendingApply) {
      return;
    }
    pendingApply = true;
    window.requestAnimationFrame(() => {
      pendingApply = false;
      applyLanguage();
    });
  }

  function startObserver() {
    if (observer || !document.body) {
      return;
    }

    observer = new MutationObserver(() => {
      if (!isApplyingLanguage && activeLanguage === "en") {
        scheduleApply();
      }
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: TRANSLATABLE_ATTRS
    });
  }

  function setLanguage(language) {
    activeLanguage = language === "en" ? "en" : "zh";
    persistLanguage(activeLanguage);
    applyLanguage();
  }

  document.addEventListener(
    "click",
	    (event) => {
	      const button = event.target.closest(TARGET_BUTTON_SELECTOR);
	      if (!button) {
	        return;
	      }
	      const fullPlatformSwitch = button.closest(".platform-switch");
	      if (fullPlatformSwitch && fullPlatformSwitch.querySelector(".platform-switch-menu")) {
	        return;
	      }

	      event.preventDefault();
	      event.stopImmediatePropagation();
	      setLanguage(activeLanguage === "en" ? "zh" : "en");
    },
    true
  );

  window.ShareClawLanguageSwitch = {
    apply: applyLanguage,
    setLanguage,
    getLanguage: () => activeLanguage
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => {
      originalDocumentTitle = document.title;
      applyLanguage();
      startObserver();
    });
  } else {
    originalDocumentTitle = document.title;
    applyLanguage();
    startObserver();
  }
})();
